### ISSUE TITLE
Fix sizing of cards in the Discovery view

### ISSUE THREAD

**Issue by erikos** [endlessm/kolibri-explore-plugin#660]
The cards in the featured channel section (_Your channels_) are small even so there are only three cards.

![Screenshot 2023-06-22 14 36 35](https://github.com/endlessm/kolibri-explore-plugin/assets/3714785/86c5855f-b344-4dc1-97c7-9ec32336bcd3)

The cards in the section (_Just for you_) are big however - they should be small.

![Screenshot 2023-06-22 14 36 26](https://github.com/endlessm/kolibri-explore-plugin/assets/3714785/61550290-d93e-4f74-884d-c833756da3cc)

**Comment by manuq** [comment]
As explained over Slack this is on purpose / by design. This is the "slidable cards" component and it fills the blanks to prevent having enlarged cards. In the Discovery tab for collections it is configured to be:
* featured channels: 4 (in large screen, 2 in medium screen, 1 in small screen)
* resources tagged "highlight" 3 (2 medium, 1 small)
* resources tagged "skill" 4 (2 medium, 1 small)
* resources tagged "career" 3 (2 medium, 1 small)
* resources tagged "curious" 4 (2 medium, 1 small)

Let's suppose we have 5 cards to show and we configure the component to have 4 cards per row. This is how it would look like:
![cards-a](https://github.com/endlessm/kolibri-explore-plugin/assets/83944/bf0fe4a5-6f57-4a89-87d5-c591bc5c6503)

Now imagine we don't fill the blank, this is what it would look like:
![cards-b](https://github.com/endlessm/kolibri-explore-plugin/assets/83944/0aa3389f-8d8c-4bc9-a289-5fff580fe008)

That is, the fifth card will look super stretched!

**Comment by manuq** [comment]
From @jofilizola new design specs https://github.com/endlessm/endless-key-content-private/issues/14#issuecomment-1585126086 "Draggable sliders: 4 cards on desktop screens (no big cards)".

**Comment by erikos** [comment]
QA in Ladybird v6.30.0 (Vanessa and Simon)
