### ISSUE TITLE
Remove the option to use a physical key with the app

### ISSUE THREAD

**Issue by erikos** [endlessm/kolibri-explore-plugin#723]
We have agreed that the support of using the app with a physical USB key should be removed - is no longer supported. This will simplify the onboarding. Also will remove a requirement that was hard to get right on multiple platforms.

The onboarding screen has to be simplified. My poor man version of the new welcome screen.

![Onboarding_Get_Started](https://github.com/endlessm/kolibri-explore-plugin/assets/3714785/460b0c76-63e2-4cc7-99fc-a518751a83e2)

![Onboarding_Get_Started_new](https://github.com/endlessm/kolibri-explore-plugin/assets/3714785/32823102-1ff3-4a24-bdf3-e7cca64986dc)

- [x] #732
- [x] https://github.com/endlessm/kolibri-installer-android/issues/171
- [x] https://github.com/endlessm/endless-key-app/issues/145
- [x] #733
- [ ] #734
- [ ] https://github.com/endlessm/endless-key-content-private/issues/94

**Comment by dbnicholson** [comment]
This is actually a fairly complex feature because (at least in the Android app, haven't checked Windows) there's tight coupling between the welcome-screen JS and the webview. I think this kind of needs to go in 3 pieces:

1. Change the initial screen so it doesn't offer the USB option.
2. Change the installers so that they no longer use the welcome-screen USB APIs
3. Drop all the welcome-screen USB APIs

In the Android app step 2 would be a massive simplification and allow dropping all the Android DocumentsProvider handling.

**Comment by jofilizola** [comment]
Layout

## Option 1:
Figma screen sizes: https://www.figma.com/file/Mwgjbi2CHUoTMdkE9aGQfP/EK-M?type=design&node-id=443%3A30695&mode=design&t=cBrUqGp3OpnwKh5C-1

- [ ] Title color change
- [ ] Background color change 
- [ ] Layout change 
- [ ] Asset change https://www.dropbox.com/scl/fi/5zmk7n48ggrg8z527akph/Welcome-cards.png?rlkey=zg5hbqjz23cj8tgwngior93tm&dl=0
- [ ] Description: add
- [ ] Steps: add 
- [ ] "Help" link to Suport page: add

![image](https://github.com/endlessm/kolibri-explore-plugin/assets/51095367/a2ade360-5295-4939-bded-afab7c4a41cd)

## Option 2:
Figma screen sizes: https://www.figma.com/file/Mwgjbi2CHUoTMdkE9aGQfP/EK-M?type=design&node-id=448%3A31849&mode=design&t=cBrUqGp3OpnwKh5C-1

- [ ] Title color change
- [ ] Background color change 
- [ ] Layout change 
- [ ] Asset change https://www.dropbox.com/scl/fi/5zmk7n48ggrg8z527akph/Welcome-cards.png?rlkey=zg5hbqjz23cj8tgwngior93tm&dl=0
- [ ] Description: add
- [ ] "Help" link to Suport page: add

![image](https://github.com/endlessm/kolibri-explore-plugin/assets/51095367/992bd4ec-e6a1-4723-9e9c-f95e2d5416d2)

**Comment by wjt** [comment]
Rather than mixing the redesign with the removal of the feature, let's track those separately. Initially we'll simply remove the option as Simon suggested; then as a follow-up, redesign the page.

**Comment by dylanmccall** [comment]
With this change, do we have some time to drop the welcome page as a separate application altogether? That is, move everything that's left from https://github.com/endlessm/kolibri-explore-plugin/tree/master/packages/welcome-screen to https://github.com/endlessm/kolibri-explore-plugin/tree/master/kolibri_explore_plugin.

The only reason we have that separate welcome-screen package is to support storing files on USB, since that choice affected how we start Kolibri. With this change, we'll always be starting Kolibri the same way, so the Explore plugin itself can deal with the welcome screen on its own.

**Comment by dbnicholson** [comment]
> With this change, do we have some time to drop the welcome page as a separate application altogether? That is, move everything that's left from https://github.com/endlessm/kolibri-explore-plugin/tree/master/packages/welcome-screen to https://github.com/endlessm/kolibri-explore-plugin/tree/master/kolibri_explore_plugin.
> 
> The only reason we have that separate welcome-screen package is to support storing files on USB, since that choice affected how we start Kolibri. With this change, we'll always be starting Kolibri the same way, so the Explore plugin itself can deal with the welcome screen on its own.

This would be great. This is a source of complexity in both the Android and Windows apps. I had a brief look at this last week and it seems like all that would be needed from the welcome screen code without the USB support would be the selection of the download pack. And if Kolibri was already running it could be a straightforward API call to the backend rather than requiring the app to provide a JS interface to call into.

**Comment by starnight** [comment]
> > With this change, do we have some time to drop the welcome page as a separate application altogether? That is, move everything that's left from https://github.com/endlessm/kolibri-explore-plugin/tree/master/packages/welcome-screen to https://github.com/endlessm/kolibri-explore-plugin/tree/master/kolibri_explore_plugin.
> > The only reason we have that separate welcome-screen package is to support storing files on USB, since that choice affected how we start Kolibri. With this change, we'll always be starting Kolibri the same way, so the Explore plugin itself can deal with the welcome screen on its own.
> 
> This would be great. This is a source of complexity in both the Android and Windows apps. I had a brief look at this last week and it seems like all that would be needed from the welcome screen code without the USB support would be the selection of the download pack. And if Kolibri was already running it could be a straightforward API call to the backend rather than requiring the app to provide a JS interface to call into.

Ack.  This reduces complexity, and helps the development of coming Endless Key on EOS.
It is worth a ticket to track.

**Comment by erikos** [comment]
This is a great idea indeed. Yes, please open a new ticket if that helps separating it from the other goals.

**Comment by dylanmccall** [comment]
Okay, I created a new ticket for that over here:

- #723

**Comment by erikos** [comment]
I created a new ticket for updating the support wiki: https://github.com/endlessm/endless-key-content-private/issues/94

**Comment by erikos** [comment]
All the of the USB support related code (Python side) has been removed from the plugin. We have two follow up tasks here. Closing this one.
