### ISSUE TITLE
Individual content download is very slow at the first launch of the app

### ISSUE THREAD

**Issue by vanessa-chang** [endlessm/kolibri-explore-plugin#739]
At the first launch of the app, after you get into the Discovery page after content pack downloaded.
Try to download an individual content, it will take a long time. (>5 mins)
The download time will reduce to 1 min after you restart the app.

Step to reproduce:
1. Install the app and Select a content pack to download
2. Get into the main Discovery page
3. Get into a channel page and select a content to download
4. Check the download time

Result: 
It will take more than 5 mins to dowload the content.
If you quit the app, it will take ~1 min to complete the download.

This issue can be reproduced in both Chromebook and Windows app.

Logs:
Chromebook (app version: 6.31-379)
[content_download.txt](https://github.com/endlessm/kolibri-explore-plugin/files/12302248/content_download.txt)

Windows (app version: 6.32.1.0)
[kolibri.txt](https://github.com/endlessm/kolibri-explore-plugin/files/12302318/kolibri.txt)

**Comment by vanessa-chang** [comment]
I attempted to idle the system for 30 minutes and then retook the test. The download speed is normal.

**Comment by erikos** [comment]
> I attempted to idle the the EK app for 30 minutes and then retook the test. The download speed is normal.

Ok, thanks for this test. This points to an issue with the downloading of the metadata in the background. So this has to be investigated.

**Comment by erikos** [comment]
Just played a bit more with it. I started the download of the individual item, and the thumbnails were already there in the channel I was looking at (Music, in the Artist pack). The first try the download took very long. The second time the app rendered unresponsive even.


![Image](https://github.com/endlessm/kolibri-explore-plugin/assets/3714785/0621f9a6-bdef-4fc1-96ca-df928c878438)

**Comment by dbnicholson** [comment]
Oh, I think there might be a much simpler fix for this. Right now we're using the defaults where kolibri starts 4 regular priority workers (can start regular or high priority jobs) and 2 high priority workers (starts only high priority jobs). The thumbnail downloads are done at regular priority while the user requested downloads are done at high priority.

So, I think we can probably just reduce the number of workers quite a bit. Something like 1 regular worker and 2 high priority workers. That way you can get 2 user initiated downloads going in parallel while the background thumbnail tasks will completely serialize. I'll experiment with that.

**Comment by erikos** [comment]
That is interesting. Also it would be a good test to turn off downloading the thumbnails and test behavior then, if that solves all of the issues. Making sure sure that we are barking up the right tree.

**Comment by dbnicholson** [comment]
I played with this before the end of the day yesterday and it seems like the app is more responsive with less background downloading. However, I immediately tried to download a document and it just spun until the thumbnails were done downloading. Since it was a high priority task it should have been scheduled immediately. I don't know what was going on there. I'm going to do a bit more debugging of the kolibri tasks system to day to try to understand it better.

**Comment by dbnicholson** [comment]
Hmm, when the download task comes in from the API it's being enqueued at regular priority. This is unlike when the task is enqueued directly from the backend and we specify the priority as high.

Ohhh, unlike the [remotechannelimport task](https://github.com/learningequality/kolibri/blob/1428c198701706339a57caa35bc2d521cbce4107/kolibri/core/content/tasks.py#L202), the [remotecontentimport task](https://github.com/learningequality/kolibri/blob/1428c198701706339a57caa35bc2d521cbce4107/kolibri/core/content/tasks.py#L227) does not specify a default high priority. Can I specify the task priority through the API? I think the default should be changed and I'll send a patch to LE while maybe making a downstream patch in our installer.

**Comment by dbnicholson** [comment]
Sent https://github.com/learningequality/kolibri/pull/11113 upstream. I think we should do this regardless of the rest of the solution here since user requested downloads should take precedence over other tasks.

The downside of reducing the number of workers is that also slows down the initial download on the welcome screen. Currently you can get 6 tasks going in parallel during initial download. That allows more of the channels from a pack to be downloaded in parallel. It also speeds up the part at the end where all the remaining channels from the collection are downloaded.

The alternative solution involves #592. Currently the way the thumbnail tasks are handled is that they're all created at once and scheduled before the collection downloader completes. Kolibri then goes and runs as many of them as there are available workers. This is really simple since we get out of the collection downloader and let Kolibri deal with it. What would be better would be scheduling the thumbnail tasks one by one so that Kolibri only runs one at a time regardless of how many workers are available.

The reason why the extra channel download is done in the collection downloader is that we need the channel metadata first so that the thumbnail nodes can be determined. Right now the only way to serialize that is to do it in the collection downloader. Instead you'd need something that reacts to completed tasks and queues the next task. You can do that with a `StorageHook`, but it would also involve storing the outstanding tasks in the database. It's not insurmountable by any means, but certainly more work.

**Comment by dbnicholson** [comment]
https://github.com/learningequality/kolibri/pull/11113 was rejected. I think we'll need to carry a downstream patch until the better alternative solution can be implemented.

**Comment by dbnicholson** [comment]
Actually, the better way would be to restore our custom `remotecontentimport` task we've used before in the explore plugin. The only difference is that it will be specified with high priority.

**Comment by dbnicholson** [comment]
I think #754 is an easy win here. It's not perfect since all the task workers are likely occupied with thumbnail tasks, so you still have to wait for one of them to complete. But it's better than before where you'd have to wait for all of them to complete because the content download task is the same priority as any outstanding thumbnail tasks.

**Comment by erikos** [comment]
Available in https://github.com/endlessm/kolibri-explore-plugin/releases/tag/v6.35.0 and in internal testing in the Android app.

**Comment by vanessa-chang** [comment]
Verified passed in Chromebook Manatee 6.38-389 & Windows 6.38.5.0
