### ISSUE TITLE
UI Localization

### ISSUE THREAD

**Issue by dbnicholson** [endlessm/kolibri-explore-plugin#760]
We want the frontend components to be localized to Spanish. For now we'll use in house translation, but it might be nice to wire up Transifex.

**Comment by dbnicholson** [comment]
That all makes sense to me, thanks for looking into it.

**Comment by pwithnall** [comment]
PR ready for some initial glancing at here: https://github.com/endlessm/kolibri-explore-plugin/pull/766, but only if you’re bored. It’s not ready for proper review yet.

A companion issue now exists with the full set of strings for translation, so we can get started on translations: https://github.com/endlessm/kolibri-explore-plugin/issues/765

I’ve filed an issue against kolibri-tools about `pyproject.toml` support, because currently the tooling only supports `setup.cfg`. https://github.com/learningequality/kolibri/issues/11146

---

For my notes, here are some of the other Kolibri plugin projects which I’ve looked at for inspiration:
 * https://github.com/learningequality/kolibri-exercise-perseus-plugin/blob/develop/package.json
 * https://github.com/learningequality/cookiecutter-kolibri-plugin
 * https://github.com/learningequality/kolibri-instant-schools-plugin/blob/develop/kolibri_instant_schools_plugin/instant_schools_settings.py
 * https://github.com/learningequality/studio/blob/d76efcf03a8c2fe6d43c67afcfd186f7b5ae667f/package.json#L12
 * https://github.com/learningequality/studio/blob/d76efcf03a8c2fe6d43c67afcfd186f7b5ae667f/package.json#L38

**Comment by pwithnall** [comment]
In #765, Joana found that there are a number of untranslatable strings in the `welcome-screen` package. I’ve filed #770 about that.

**Comment by pwithnall** [comment]
I put together a rough (rubbish) Spanish translation today in order to test the frontend translation functions, and have a result!

![image](https://github.com/endlessm/kolibri-explore-plugin/assets/53172/5171506f-bb0e-4774-9b94-0f5c5a31681d)

That didn’t actually need any frontend changes to start using the JSON files containing the translations. As long as the JSON file is named correctly, Kolibri’s webpack bundle hook will pick it up via its well-known name and inject it into the frontend.

I’ve added a fixup commit to explain that in the docs.

As can be seen from the screenshot, there are still some English strings on the main page. That is separate from #765 as this isn’t the welcome screen. I’ll look into making sure they’re translated tomorrow, and then this issue should be ready for review and merging.

**Comment by pwithnall** [comment]
> As can be seen from the screenshot, there are still some English strings on the main page. That is separate from #765 as this isn’t the welcome screen. I’ll look into making sure they’re translated tomorrow, and then this issue should be ready for review and merging.

⇒ #771, #772, #773
