### ISSUE TITLE
Key on Android: select Spanish content pack based on locale

### ISSUE THREAD

**Issue by erikos** [endlessm/kolibri-explore-plugin#857]
Follow up of _Select Spanish content pack based on locale_ #786

In the Flatpak this is working fine. On the Chromebook this is not working yet. The app still shows an English UI even though the system locale is set to Spanish.

**Comment by manuq** [comment]
@erikos I think the target for this issue should be the kolibri-installer-android repository, not this one.

@dbnicholson @dylanmccall please correct me if I'm wrong. Isn't English the default in Android because of the [`src/automatic_provision.json`](https://github.com/endlessm/kolibri-installer-android/blob/601a04d408ebb6595b4d47aafc11bfffaf31bba5/src/automatic_provision.json#L13) file has language hardcoded to "en"?

**Comment by erikos** [comment]
I opened https://github.com/endlessm/kolibri-installer-android/issues/187

**Comment by dbnicholson** [comment]
> @dbnicholson @dylanmccall please correct me if I'm wrong. Isn't English the default in Android because of the [`src/automatic_provision.json`](https://github.com/endlessm/kolibri-installer-android/blob/601a04d408ebb6595b4d47aafc11bfffaf31bba5/src/automatic_provision.json#L13) file has language hardcoded to "en"?

That does seem like the case. I'll follow up in https://github.com/endlessm/kolibri-installer-android/issues/187.
