### ISSUE TITLE
Windows app: Spanish setting only applies on the loading screen

### ISSUE THREAD

**Issue by vanessa-chang** [endlessm/kolibri-explore-plugin#861]
In the latest Windows app: 7.4.1.0

OS language settings
<img width="365" alt="Captura de pantalla 2023-09-28 202440" src="https://github.com/endlessm/kolibri-explore-plugin/assets/31236978/7f791880-5352-4f02-ac7c-4f734fd38c68">

The loading screen is in Spanish but the following screens are still in English.

<img width="960" alt="Captura de pantalla 2023-09-28 201223" src="https://github.com/endlessm/kolibri-explore-plugin/assets/31236978/441d31c9-f395-4d68-8088-6b06c550acc6">
<img width="960" alt="Captura de pantalla 2023-09-28 201251" src="https://github.com/endlessm/kolibri-explore-plugin/assets/31236978/65ace7d4-15de-479d-bf77-47a1bc008d69">

**Comment by manuq** [comment]
This is probably because the loading screen follows to the browser language. But the other screens follow the Kolibri language, which is hardcoded to "en" in https://github.com/endlessm/endless-key-app/blob/9012dfef76fb245b962ebc0ed27c3def47fba54e/kolibri-electron/src/automatic_provision.json#L13

By the way, this ticket should target the https://github.com/endlessm/endless-key-app repository. Closing this one as invalid.
